### ISSUE TITLE
Punch didn't reflect to the account and displayed an absent record at time records

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#100]
**Describe the bug**
A certain employee applied a punch on dates 06/14-16 but didn't reflect into the system and in the admin account

**To Reproduce**
4. See the error

**Expected behavior**
Time record should update the record as Present, showing the details of the punch

**Screenshots**
![0-02-06-6136301d3ea82ccd0d5e22f8a72c45c5a60cdd1ac56d9982d625cfd0e0f93541_acafb310c5218a8d](https://user-images.githubusercontent.com/84363701/122343319-2a70e900-cf78-11eb-8da0-1a5be4262c86.jpg)

**Additional context**
Upon duplicating the same procedure at the end of the admin account, the punch in and out were recorded.

**Comment by Peterdelapena** [comment]
Kindly check the logs of the following employees:
Cruz, Charmaine
Ricarte, Shienah
Oris, John Paul
![image](https://user-images.githubusercontent.com/84363701/122496463-65c5f300-d01e-11eb-9e5e-37827498bb32.png)

**Comment by byron02** [comment]
Bug Type: Data Issue

Org:DENR-EMB-NCR

Cause of Bug: Incorrect Register ID and Register Cutoff ID

Approach: Adjusted Register ID and Cutoff ID for the month of June

Approached Applied: June 18, 2021

**Comment by Peterdelapena** [comment]
Fixes validated, marked as closed
