### ISSUE TITLE
Master list updating for DENR

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#101]
**Is your feature request related to a problem? Please describe.**
 Removal of the personnel tagged as Resigned, Terminated, and Deceased. The said personnel kept on appearing during the generation of DTR. For updating pls, Thank you

**Describe the solution you'd like**
Removal of the personnel

**Additional context**
[EMPLOYEE UPDATING HRIS 6.17.21 (1).xlsx](https://github.com/vasavah/vasavah-qa-trainees/files/6706005/EMPLOYEE.UPDATING.HRIS.6.17.21.1.xlsx)

**Comment by AnyaCee** [comment]
issue has been fixed, marked as closed
