### ISSUE TITLE
Phone locations didn't reflect in the system upon Kiosk Authorization

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#103]
**Describe the bug**
Phone locations didn't reflect in the system upon Kiosk Authorization

**To Reproduce**
1. Go to 'https://kiosk.kodanda.cloud/login/denr-emb-ncr' on your phone
2. Turn on phone location
3. Copy Authorization code
4. Activate it on APP
5. See the error

**Expected behavior**
Phone location should be shown in the Kiosk autorization

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/122498867-6fe9f080-d022-11eb-8b26-6187f4c87324.png)

Phone Used and Browser:

Honey-samsung/mozilla
Michelle-realme/google
Lady-iphone /safari

Note: I recommend that we activate kiosk authorization for the admin account so you can test also on your mobile device if the location would be saved.

**Comment by AnyaCee** [comment]
issue has been fixed, marked as fixed

**Comment by AnyaCee** [comment]
Based on the recent activation of KIosk Location per employee. The following personnel is able to generate activation code but the Kiosk Authorization record reflects "no location". Attached is the list (excel) of personnel with the unreflected locations. 
![image](https://user-images.githubusercontent.com/84363875/130718410-55157c5b-8938-45f5-80cf-6cdad3789836.png)
File: https://docs.google.com/spreadsheets/d/1GpwpVZUdod3Wt_NdkXG8KEpocKZ3urn0/edit#gid=1769595869
