### ISSUE TITLE
Disappearing logs upon opening Kiosk on the user's mobile phones

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#104]
**Describe the bug**
Disappearing logs upon opening Kiosk on the user's mobile phones
![image](https://user-images.githubusercontent.com/84363701/122499343-585f3780-d023-11eb-86b6-d9c3acdb617c.png)

Users who reported the concern:

Joy Anne Mancera
Charmaine Gonzales
Lady Alfonso

**Comment by AnyaCee** [comment]
issue has been fixed, marked as closed
