### ISSUE TITLE
Dashboard Alerts for Ticket Processors

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#107]
SLA Monitoring Ticket Resolutions -> Use business days instead of Calendar days
![image](https://user-images.githubusercontent.com/84363701/122502315-fb668000-d028-11eb-8ca4-3dc15c34a470.png)

**Comment by Peterdelapena** [comment]
SLA Monitoring Ticket Resolutions -> Site Admins can change the SLAs after benchmarking has been completed internally
![image](https://user-images.githubusercontent.com/84363701/122502616-86e01100-d029-11eb-9f08-62513691bc40.png)

**Comment by Peterdelapena** [comment]
There are no screenshots yet from the client

**Comment by Peterdelapena** [comment]
Upon selecting priority 1 and 2 on ticket creation, the SLA due date selects a date that falls to the desired business days.
But for priority 3-5, an error occurs in the estimation of SLA due date. 

![image](https://user-images.githubusercontent.com/84363701/122536196-dab51f00-d056-11eb-9d8f-e9f7a3796a30.png)
![image](https://user-images.githubusercontent.com/84363701/122536225-e274c380-d056-11eb-8cb7-d6dee3faf87c.png)
![image](https://user-images.githubusercontent.com/84363701/122536272-f28ca300-d056-11eb-8c12-03b5ba05575a.png)
 
bug occurs in the year selection/estimation of SLA due date

**Comment by Peterdelapena** [comment]
Fixes on editing SLA due date was done and working
![image](https://user-images.githubusercontent.com/84363701/122869330-af844580-d35e-11eb-9855-03d204f7998c.png)

**Comment by AnyaCee** [comment]
marked as closed
