### ISSUE TITLE
 Admin dashboard queue Provision for VIP Queue (tagging of requestor to be done by TBI)

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#108]
There should be an added queue provision for VIP on the admin dashboard.

The purpose is for tagging of requestor to be done by TBI
![image](https://user-images.githubusercontent.com/84363701/122530520-21077f80-d051-11eb-99fd-139a12d09347.png)

Added Information regarding this ticket is for pending

**Comment by AnyaCee** [comment]
marked as closed
