### ISSUE TITLE
Under admin dashboard, please include number of  Unread New Messages/New Comments

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#109]
Please include number of  Unread New Messages/New Comments under the admin dashboard

![image](https://user-images.githubusercontent.com/84363701/122530796-72b00a00-d051-11eb-96f8-4e045207d330.png)

 
Added Information regarding this ticket is for pending

**Comment by AnyaCee** [comment]
marked as closed
