### ISSUE TITLE
Requesting for checking of Wyll Paglinawan’s account, he can’t still proceed on the development portion – part 3.

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#111]
**Describe the bug**
Requesting for checking of Wyll Paglinawan’s account, he can’t still proceed on the development portion – part 3.
Career Level = Senior Associate

![image](https://user-images.githubusercontent.com/84363701/122720792-78e8f500-d2a2-11eb-87b2-437afb3605ac.png)
![image](https://user-images.githubusercontent.com/84363701/122722044-df224780-d2a3-11eb-8495-73ac3fdfca35.png)

**Comment by AnyaCee** [comment]
marked as closed
