### ISSUE TITLE
Final Rater rating override and approval is gone

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#113]
**Describe the bug**
Final Rater rating override and approval is gone, can't proceed to HR approval and employee final rating 

![image](https://user-images.githubusercontent.com/84363701/122857468-1b5cb300-d34b-11eb-9133-68972a9c21a0.png)

**Comment by AnyaCee** [comment]
issue has been fixed, marked as closed
