### ISSUE TITLE
There are some employees with zero daily / Hourly rates 

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#14]
**Describe the bug**
There are some employees with zero daily rates, Hourly rates, Tax shield, and Gross salary

**To Reproduce**

1. Go to ' Employees - HR'
2. Click 'Profile' of employees and check who has the error
3. Check the compensation details if the employee has the error

**Expected behavior**
There should be data on the Daily/ Hourly rates of the employees

**Screenshots**
 
![STEP 6-8](https://user-images.githubusercontent.com/84363701/119317810-199bc300-bcab-11eb-8347-bfa0c34687b8.JPG)

![image](https://user-images.githubusercontent.com/84363701/119316924-24098d00-bcaa-11eb-8a1f-6bce2c340514.png)

[Github #14  TICKET VALIDATION 5-24-21.xlsx](https://github.com/vasavah/vasavah-qa-trainees/files/6530890/Github.14.TICKET.VALIDATION.5-24-21.xlsx)

**Desktop (please complete the following information):**
OS: [win10]
Browser [chrome]
Version [90.0.4430.212]

** Smartphone (please complete the following information):**

Device: [n/a]
OS: [n/a]
Browser [n/a]
Version [n/a]

**Additional context**
As per testing, some employees have zero Daily/Hourly rates to their compensation details. The ticket was found to be valid and will fall into a bug issue.

**Comment by AnyaCee** [comment]
issue has been fixed, marked as closed
