### ISSUE TITLE
No punch-in buttons on the employee’s account

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#143]
No punch-in buttons on the employee’s account. The system said that “You are on leave today”. Up until now the employee still can’t access her kodanda kiosk. 
·         The employee applied for half-day leave on June 21, 2021, and was approved.
·         Today (June 23) as per checking her account, yesterday was ABSENT, and still can’t punch in and out today.
·         Employee username: arsilapan  
 
![Account that doesn't have access from previous cut-off](https://user-images.githubusercontent.com/84363701/123197673-71ae2b00-d4de-11eb-99c0-b72ec5a5e2f1.jpg)
![Kodanda concern for punch buttons 2](https://user-images.githubusercontent.com/84363701/123197681-7377ee80-d4de-11eb-9d57-41ee8c332f70.jpg)
![Kodanda concern for punch buttons 1](https://user-images.githubusercontent.com/84363701/123197683-74a91b80-d4de-11eb-9b9c-6a62e9a990c2.jpg)

**Comment by AnyaCee** [comment]
ticket marked as close
