### ISSUE TITLE
Mid-year / Manager's Ratings and comments didn't appear in the interface of employee

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#148]
Mid-year / Manager's Ratings and comments didn't appear in the interface of employee's appraisals the only thing that should be hidden is the Overall rating.
![image](https://user-images.githubusercontent.com/84363701/123245868-cf129e00-d517-11eb-9c91-035f406f0495.png)

**Comment by AnyaCee** [comment]
ticket marked as closed
