### ISSUE TITLE
MTA Email Template

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#173]
MTA Email Template
Org: Smudgecorp, smudgetest, aceic, acen, aces and other org that has MTA Matrix
Type: Enhancement
Description: No email template created for MTA.

Steps on how to reproduce the error:
1. Create an MTA application on the employee side
2. Submit the application
3. Check who is the approvers of the employee that you used
4. Login in gmail using the approver's email address
5. Check the email of the MTA pending applications
6. See the error

Expected Result: It should display the details of the MTA applications.

**Comment by jeannie06** [comment]
Hi, I've already emailed the MTA email template to @byron02. Let's just wait for his go signal once he already fixed the backend. Thanks!

**Comment by jeannie06** [comment]
This is ready for QA in release, please check also the landing page that I've created

**Pull Request:** https://github.com/vasavah/kodanda-hcm-web/pull/86

**Type:** Enhancement

**Approach:** Create landing page for MTA and update footer, it should match in the footer of the email template

**Approached Applied:** August 05, 2021

**Branch Name:** feature/ApplicationsLandingPage

**Comment by AnyaCee** [comment]
![image](https://user-images.githubusercontent.com/84363875/128506918-88c0d50b-98cc-479d-a35d-40a994ae5412.png)

This is the screenshot of an email for applied MTA. Should it be "MTA" and not "Overtime"? and also the logo is also cracked?

**Comment by AnyaCee** [comment]
Proof of fixes ![image](https://user-images.githubusercontent.com/84363875/128707283-d88ee117-da66-46b2-a126-7854964b7884.png)
