### ISSUE TITLE
Descriptions to be included in the 9box - L&D

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#195]
**Is your feature request related to a problem? Please describe.**
Only to include descriptions in the 9Box
![image](https://user-images.githubusercontent.com/84363701/128282485-92f7a15a-4319-462c-a704-cc90897b854a.png)

**System:**
L&D

**Additional context**
"ms. chiara asked for the descriptions to be included in the 9box - make it na lang tooltip para pag hover makita yung descriptions per box and also the one on the left yung potentials"

**Comment by jeannie06** [comment]
Hi @Peterdelapena, this is ready for QA.

**Pull Request:** https://github.com/vasavah/kodanda-hcm-web/pull/28

**Org:** smudgetest

**username:** andre.montemar

**Type:** Enhancement

**Approach:** 
1. Create schema that contain boxes data like category, number, descriptions and employees then create a loop to display it in the table
2.  Create popover, it will display the descriptions of the specific box once user hover it

**Approached Applied:** August 05, 2021

**Branch Name:** feature/learningAndDevelopment

**Note:** The bluish colors are the updated and approved colors for the 9 boxes

![image](https://user-images.githubusercontent.com/51081897/128338062-e3ceb4f0-eb2e-4b9e-ae99-25cf2d2c7a71.png)

![image](https://user-images.githubusercontent.com/51081897/128338084-fe5237e0-4007-448b-9c6c-195451712604.png)
