### ISSUE TITLE
Punch in and out buttons upon logging in is good. Maybe we can have the punch in and out buttons bigger by 30% so employees can spot it easily

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#198]
ORG: ACE HO
TYPE: adjustment

Describe the solution you'd like
Can the punch in and out buttons bigger by 30% so employees can spot it easily.

Steps to see where to adjust:
1. Login into kiosk with valid creds
2. see punch buttons

Screenshot:
![image](https://user-images.githubusercontent.com/84363875/128287022-b1cd0f8d-c15d-4f44-9ed1-9ac9701c9a27.png)

**Comment by jeannie06** [comment]
This is now for code review, will update the sheet once it's ready for QA. Thanks!

**Pull Request:** https://github.com/vasavah/kodanda-kiosk-web/pull/6

**Type:** Enhancement

**Approach:** Adjust size of the buttons, margin, padding and font size.

**Approached Applied:** Sept 14, 2021

**Branch Name:** feature/punchButtons

**Updated Punch Buttons:**

<img width="960" alt="2021-09-14" src="https://user-images.githubusercontent.com/51081897/133193651-e867a4d1-3051-4ed1-bd8d-6cf12822b37a.png">

<img width="182" alt="2021-09-14 (1)" src="https://user-images.githubusercontent.com/51081897/133193657-12aaf4a4-4cac-4652-8ae6-2a8b27901d92.png">


> ORG: ACE HO
> TYPE: adjustment
> 
> Describe the solution you'd like
> Can the punch in and out buttons bigger by 30% so employees can spot it easily.
> 
> Steps to see where to adjust:
> 
> 1. Login into kiosk with valid creds
> 2. see punch buttons
> 
> Screenshot:
> ![image](https://user-images.githubusercontent.com/84363875/128287022-b1cd0f8d-c15d-4f44-9ed1-9ac9701c9a27.png)

**Comment by AnyaCee** [comment]
marked as closed
