### ISSUE TITLE
Request Training Form

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#217]
**Page**
Request Training Form

**Module**
Training Requests

**Revisions for Employee/Admin/HR**

- List all added trainings in Training Course
- Add Others in Training Classification then if user selected others training course will be free text field
- Auto-populate Date From,  Date To and Training hours if user selected In House or External in Training Classification
- In Location, change On-Site to Classroom and auto-select the selected training type in Add Training if user selected In House or External in Training Classification

**Revisions for Admin/HR**

- "Add Training Assignment radio button - Options (Planned, Additional, Ad Hoc)"

**Comment by AnyaCee** [comment]
Auto-populate Date From, Date To and Training hours if user selected In House or External in Training Classification is not working 
![image](https://user-images.githubusercontent.com/84363875/128964492-8590fc53-c184-43c8-97ed-da64c58d7aee.png)

**Comment by AnyaCee** [comment]
In Location, change On-Site to Classroom 
![image](https://user-images.githubusercontent.com/84363875/128964695-0302214f-b89c-4d8d-ab9d-cbff3e224629.png)

**Comment by AnyaCee** [comment]
auto-select the selected training type in Add Training if user selected In House or External in Training Classification
![image](https://user-images.githubusercontent.com/84363875/128965479-67527730-610d-4e3d-8e32-67dbd29619a6.png)

**Comment by AnyaCee** [comment]
"Add Training Assignment radio button - Options (Planned, Additional, Ad Hoc)"

Can't see this feature

**Comment by jeannie06** [comment]
Hi @AnyaCee, we have a changes here. You can see this in Assign Training. Thanks!

"Add Training Assignment radio button - Options (Planned, Additional, Ad Hoc)"
