### ISSUE TITLE
FMA Allowance of Php 12,500 is finite. This should only be 1 time last 1/15/2021 but it reflected during May 15 payroll

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#238]
Org: CIP
Type: Bug
Scenario:

FMA Allowance of Php 12,500 is finite. This should only be 1 time last 1/15/2021 but it reflected during May 15 payroll

![image](https://user-images.githubusercontent.com/84363875/129027158-bc75e4ba-c21d-4437-8366-53b0dde26abe.png)

**Comment by AnyaCee** [comment]
![image](https://user-images.githubusercontent.com/84363875/129131140-85422298-2e6a-42be-8bbe-0d8096622209.png)

**Comment by Peterdelapena** [comment]
Fixes validated, Ticket now marked as Closed.
