### ISSUE TITLE
Rice and Laundry Allowance is Php 2,000 every month but it reflected as 166.67

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#239]
**Describe the bug**
Rice and Laundry Allowance is Php 2,000 every month but it reflected as 166.67
Org: CIP
Type: Bug
Scenario:
![image](https://user-images.githubusercontent.com/84363875/129027354-98efd6c3-bd35-4794-a270-89e9184948ea.png)

**Comment by AnyaCee** [comment]
![image](https://user-images.githubusercontent.com/84363875/129131413-96f313a6-0432-4119-8ff4-90d232295a55.png)

**Comment by byron02** [comment]
Rice and Laundry Allowance is Php 2,000 every month but it reflected as 166.67 - Invalid, naka finite yung total amount is divided by 12 po
![image](https://user-images.githubusercontent.com/51081259/129315322-5767642a-50f6-4735-b947-de561c1808f1.png)
![image](https://user-images.githubusercontent.com/51081259/129315328-73687a3b-0780-494e-9387-7b901fccb3df.png)

**Comment by Peterdelapena** [comment]
Fixes validated, Ticket now marked as Closed.
