### ISSUE TITLE
Checked the "Same as current address" button first before filling up current address doesn't auto fill the permanent address

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#256]
org: smudge corp.
Type: enhancement

Steps to reproduce:
1. Check the "Same as address" checkbox firsrt
2. Enter data in the current address
3. see an error

![image](https://user-images.githubusercontent.com/84363875/129879612-6126bc37-2355-48bc-8a42-f2d67ac2773d.png)

**Comment by jeannie06** [comment]
Hi @AnyaCee, this is now for code review. I'll update you when it's ready for QA. Thanks !

**Pull Request:** https://github.com/vasavah/kodanda-hcm-web/pull/117

**Approach:** Set new functions to update changes in current address fields

**Approached Applied:** August 18, 2021

**Branch Name:** bugfix/ers

**Comment by AnyaCee** [comment]
newly added employee and other employee doesn't appear on ERS.

Required Fields: Required Fields are asked one by one
Add comment ERS will be moved to another ticket

Add comment ERS will be moved to another ticket
https://github.com/vasavah/vasavah-qa-trainees/issues/257

**Comment by Peterdelapena** [comment]
Fixes validated, ticket marked as closed
