### ISSUE TITLE
Added Holiday is not reflecting on TAR

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#263]
Org: ACES, ACEN, ACEIC
Type: Bug

**Describe the bug**
Added Holiday is not reflecting on TAR

**To Reproduce**
1. Add holiday on holiday management
2. go to register cut-off and generate TAR
3. see error no, holiday found even on-time records

**Expected behavior**
Must have a holiday

**Screenshots**

holiday
![image](https://user-images.githubusercontent.com/84363875/130555771-e42d6c05-cfaf-4f93-9a81-38e4d7d28553.png)

Time records
![image](https://user-images.githubusercontent.com/84363875/130555826-7a4e2fec-94b7-4f20-9c31-089e0d3273f5.png)

TAR
![image](https://user-images.githubusercontent.com/84363875/130555856-bfb17d49-7c5b-42f5-8833-f6b4017e13c4.png)

**Comment by byron02** [comment]
![image](https://user-images.githubusercontent.com/51081259/130901007-db068aae-d4f9-48be-a309-e48ca35b4ff4.png)
![image](https://user-images.githubusercontent.com/51081259/130901440-ad67035d-3b5c-4060-8c6c-acc994198875.png)
Upon checking, Please revalidate
