### ISSUE TITLE
There are no portion for Manager’s rating as well as there are no ratings from the employee. To part 1 deliverables

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#286]
**Describe the bug**
Joel’s Kodanda Performance Appraisal was submitted to his Immediate Superior Jaime T. Hiquiana.
 
In which, in part I, there is no portion for Manager’s rating as well as there are no ratings from the employee.
 
Though in part II, there are portions for the Manager’s rating.

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/130889264-ea2c10d3-124b-478d-9203-a9230f3727d0.png)

![image](https://user-images.githubusercontent.com/84363701/130889310-f85d17b8-9f6c-4652-94d3-e2416eaacece.png)

**QA's end:**
![image](https://user-images.githubusercontent.com/84363701/130889350-b0b6db83-e2f9-42f9-a835-39c34516f174.png)
![image](https://user-images.githubusercontent.com/84363701/130889377-a085ba7c-1c09-4d44-8f96-8678938ba7d7.png)

**Comment by khimpVasavah** [comment]
There's really no portion there because that KRA is assigned to Apolo Castillo, so the field will be visible on apolo castillo's account on that KRA

**Comment by Peterdelapena** [comment]
Can we change the setting of the manager to "Jaime Jr. Hiquiana" just to show the part 1 deliverables?

**Comment by khimpVasavah** [comment]
yes
