### ISSUE TITLE
His Immediate Supervisor cannot access his account.

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#287]
**Describe the bug**

Kindly check appraisal account of Engr. Jayson A. Racal of Bulacan Thermal.  His Immediate Supervisor cannot access his account.

**Account: **
Arturo D. Mendoza – mendoza.ad
Jayson A. Racal  -racal.ja

**Expected behavior**
Immediate supervisor should have an access to the appraisals

**Screenshots**
Upon checking the appraisals by QA:
![image](https://user-images.githubusercontent.com/84363701/130890759-1cdf1f5d-f619-4ae5-8bdf-8b19d711f011.png)

**Comment by khimpVasavah** [comment]
did the manager submit this appraisal?

**Comment by Peterdelapena** [comment]
Follow up report: 
"His IS cannot enter his rating for his employee."
