### ISSUE TITLE
Error in Performance Appraisal Form of Kyla Samson

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#296]
System: PA
Type: bug

**Describe the bug**
Error in Performance Appraisal Form of Kyla Samson

I have assigned a performance appraisal form to Kyla Kamille Samson and I was shocked to know that there’s already pre-assigned deliverables that are actually copied from one of the employees under Legal & Regulatory.
Please see attached copy of her appraisal form.

Further, there’s also conversation under her discussion board. See the below screenshot.
![image](https://user-images.githubusercontent.com/84363875/131438857-1c5f8c75-8142-4474-80e2-9677e099ef66.png)

File attached:
https://docs.google.com/document/d/1MoawvA6Q-UXipNltkSpfbTrlU72OMWtXV37qIhkVWig/edit

**Comment by Peterdelapena** [comment]
Fixes validated, Marked as closed
