### ISSUE TITLE
revert the appraisal form of Ma. Cenecia Razonable to manager’s assessment phase

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#300]
System: PA
Type: Bug

As per checking, the appraisal form is now at the approval phase of her performance objectives which shouldn’t be the case since the employee had already accomplished her self-assessment

Scenario:
I was doing my assessment for employee 030287 and upon finishing, I clicked the submit button.
However, since loading took time (I was probably impatient 0_0), I clicked the save as drafts button and the page lead me back to the objective setting approval.
Which means that the self-assessment of the employee and my assessment to her is gone.
 
Is it possible to revert it to where I was about to submit my assessment to employee 030287 (around prior to 7:40PM of today, August 28)?

**Comment by Peterdelapena** [comment]
Requesting for the password reset for Esther Marie Amular-Bantog.
 
User ID: bantog.ea

**Comment by Peterdelapena** [comment]
![image](https://user-images.githubusercontent.com/84363701/131488369-679ea4c9-82f1-4fe3-a9ae-66fdb48a3fc4.png)

**Comment by Peterdelapena** [comment]
TIcket marked as closed
