### ISSUE TITLE
No attachment  part on creating a ticket

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#315]
System: WMS-VCI
Type: Bug

No attachment  part on creating a ticket

Steps to see the error:
1. Click L1/L2 QA under Queues
2. create a ticket
3. scroll down
4. see error

has attachment filed on view
![image](https://user-images.githubusercontent.com/84363875/131628933-60b48096-f402-40fa-a580-98e691e20eb0.png)

**Comment by AnyaCee** [comment]
Can attach only one attachment

Expected result: can add 2 or more
![image](https://user-images.githubusercontent.com/84363875/132206415-2f2ecc8d-bec0-4492-9147-6fcf4f0e0eba.png)

**Comment by byron02** [comment]
As per our feature. Multiple attachments are not available for now. This will be an enhancement for our RBE. For the workaround, Other attachments can be done on the comment section/discussion board.
