### ISSUE TITLE
Multiple attachments

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#344]
System: WMS-VCI
Type: Enhancement

Multiple attachments

Steps to see where  the enhancement is:
1. Click L1/L2 under Queues
2. create a ticket
3. scroll down
4. see user can only attach one

![image](https://user-images.githubusercontent.com/84363875/132294433-24860f95-f65c-415a-861c-73e508bc2b3f.png)

**Comment by AnyaCee** [comment]
Also add "x" button to remove the attachmented file

**Comment by jeannie06** [comment]
This is now for code review, will update the sheet once it is ready for QA. Thanks!

**Pull Request:** https://github.com/vasavah/kodanda-wms-web/pull/26

**Type:** Enhancement

**Approach:** 
1. Set the selected file to the array
2. Create a loop to display the selected files
3. Set a new conditions to display the Add Attachment button and "x" if file upload button was set into multiple upload in the vinculum.

**Approached Applied:** Sept 09, 2021

**Branch Name:** feature/multipleAttachments

**Comment by AnyaCee** [comment]
for TBI : there is still no multiple attachments on the support queue part on creating a ticket

![image](https://user-images.githubusercontent.com/84363875/132635109-8eea6399-e377-473f-ac1d-d87abc3f5b35.png)

and on the requestor queue, multiple attachments are not showing on creating ticket:

Requested:
![image](https://user-images.githubusercontent.com/84363875/132635785-40d34497-7fd4-45df-8286-e403c62cbfca.png)

Create ticket Page
![image](https://user-images.githubusercontent.com/84363875/132635917-ff0cb8fd-1639-4743-ab92-2edffeb5868a.png)

**Comment by jeannie06** [comment]
Please check it again. Thank you!

![image](https://user-images.githubusercontent.com/51081897/132654664-53a923f6-0bff-4dc1-bee6-5765d1663a8c.png)


> for TBI : there is still no multiple attachments on the support queue part on creating a ticket
> 
> ![image](https://user-images.githubusercontent.com/84363875/132635109-8eea6399-e377-473f-ac1d-d87abc3f5b35.png)
> 
> and on the requestor queue, multiple attachments are not showing on creating ticket:
> 
> Requested:
> ![image](https://user-images.githubusercontent.com/84363875/132635785-40d34497-7fd4-45df-8286-e403c62cbfca.png)
> 
> Create ticket Page
> ![image](https://user-images.githubusercontent.com/84363875/132635917-ff0cb8fd-1639-4743-ab92-2edffeb5868a.png)

**Comment by AnyaCee** [comment]
![image](https://user-images.githubusercontent.com/84363875/135047577-f321a94c-e8a4-4a58-b899-e78fba0e963e.png)

There's still no "X" button on discussion dashboard

**Comment by AnyaCee** [comment]
Reason of returned:
There's a button but the button is not working, it's not deleting the attached file
