### ISSUE TITLE
Unable to search project in 2 words

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#36]
**Is your feature request related to a problem? Please describe.**
When searching for tickets via specified service, searching for 1 specific word eg internet, it will show all tickets related to internet service and all searched with laptop word shows all service with the laptop. However, when searching with more than one word in service eg internet laptop, no tickets are shown in the display section. However, is it intended to be strictly specified, or should be able to search for all tickets with all words input

**Describe the solution you'd like**
Allow the user to have access to searching for jobs using a 2 or more keywords

**Describe alternatives you've considered**
Provide an extra tab that separates the keywords upon searching.

**Additional context**
![image](https://user-images.githubusercontent.com/84363701/120962856-1fa59f80-c793-11eb-8498-db41092e7696.png)
As per testing, the fixes in the system was valid and marked as closed

**Comment by AnyaCee** [comment]
enhancement fixed, marked as closed
