### ISSUE TITLE
There are no alerts regarding to the tickets created and assigned to self account

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#37]
**Describe the bug**
When creating a new ticket and assigning it to self, there are no alerts in being assigned a new ticket.

**To Reproduce**
1. Go to 'Queue page'
2. Select type of Queue
3. Scroll down to 'Job lists'
4. Click on 'Create job'
5. Fill up the required field
6. Scroll down to 'bottom field'
7. Assign job to self
8. Save the job
4. See the error

**Expected behavior**
A created job should notify to self as it is assigned to the account

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/120963764-c0488f00-c794-11eb-9e81-20d1bfe40dfc.png)
![image](https://user-images.githubusercontent.com/84363701/120963788-ca6a8d80-c794-11eb-844f-89524bc6be29.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Upon validating the fixes, the expected result reflects the actual result which marks the tickets as resolved/closed

**Comment by AnyaCee** [comment]
bug fixed, marked as closed
