### ISSUE TITLE
Error 404 on viewing the profile

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#38]
**Describe the bug**
Error 404 upon viewing the profile

**To Reproduce**
1. Go to 'view profile'
2. See the error

**Expected behavior**
The ystem should load the correct landing page on viewing the profile.

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/120964157-6c8a7580-c795-11eb-99e4-49bfdac0e458.png)

![image](https://user-images.githubusercontent.com/84363701/120964125-5aa8d280-c795-11eb-83f4-f9526b1e903c.png)
The system should display the following interface

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
As per testing, the fixes on the system found to be valid and marked as resolve/closed

**Comment by AnyaCee** [comment]
bug fixed, marked as closed
