### ISSUE TITLE
Jobs status not updating

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#41]
**Describe the bug**
Job Status widget not updating

**To Reproduce**

1. Go to 'support page'
2. Check the number of 'open jobs'
3. Scroll down to 'List of jobs'
4. Click 'view' on a specific job
5. Edit status of the specific job
6. Go back to the main page
7. See the error in the 'Jobs by Status'

**Expected behavior**
The system should update the changes of the tickets' status at the 'Job by Status'

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/120966989-8b8b0680-c799-11eb-8256-8099866a78b2.png)
![image](https://user-images.githubusercontent.com/84363701/120967008-90e85100-c799-11eb-9ee8-45e4c0642e6e.png)
![image](https://user-images.githubusercontent.com/84363701/120967022-95ad0500-c799-11eb-90cd-f083b060d363.png)
![image](https://user-images.githubusercontent.com/84363701/120967029-98a7f580-c799-11eb-9168-4a3cdd153bc9.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
As per duplicating the problem, there are no more issues found. Therefore the fixes were resolved and marked as closed.

**Comment by AnyaCee** [comment]
bug fixed, marked as closed
