### ISSUE TITLE
Profile photo was not changed and an error to the upper right logo 

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#44]
**Describe the bug**
After uploading, the photo was not changed and the smaller photo in the upper right became an error

**To Reproduce**
1. Go to 'View Profile'
2. Click 'Choose file'
3. Select a file 
4. See the error

**Expected behavior**
The system should allow the changes to the account's profile picture

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/120968651-b2e2d300-c79b-11eb-8198-e7d2ac5618b7.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
As per testing, the user has an access on changing its profile picture which marks the fixes as valid, and for close.

**Comment by AnyaCee** [comment]
bug has been fixed, marked as closed
