### ISSUE TITLE
Timer went up from 4mins to 8hrs after refreshing

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#47]
**Describe the bug**
After 4 mins, stopped the timer and upon refreshing the page, the timer went up to 8hrs. This can incur confusion within the users answering tickets and if left unchecked, supervisors can question users for answering tickets too long for this bug.

**To Reproduce**
1. Go to 'support page'
2. Scroll down to 'List of jobs'
3. Click 'view' on a specific job
4. Edit job information
5. Click 'start' of the timer
6. Refresh the page
6. See the error

**Expected behavior**
Timer should be consistent with the time it had been recording

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/120979071-c8f69080-c7a7-11eb-9740-01f0353382ec.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
As per testing, the timer did what is expected. The fixes was valid and marked as resolved/closed

**Comment by AnyaCee** [comment]
bug has been fixed, marked as closed
