### ISSUE TITLE
Unchecking the 'Has Default Competency' selection, removes the deliverables that has been made by the user.

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#58]
**Describe the bug**
Upon creating a template, unchecking the 'Has Default Competency' selection removes the deliverables that have been made by the user.

**To Reproduce**
1. Go to 'Performance Review'
2. Click on 'Create Appraisal Template'
3. Select 'Objectives'
4. Click 'Add Deliverables'
5. Fill up ' Deliverables'
6. Click 'Has Default Competency'
7. Unclick 'Has Default Competency'
8. See error

**Expected behavior**
The system should go back to its previous application, w out deleting/removing the whole deliverables

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/121341586-63470780-c953-11eb-84ba-92be8b7ba0e6.png)
![image](https://user-images.githubusercontent.com/84363701/121341673-76f26e00-c953-11eb-953a-db83312305bf.png)
![image](https://user-images.githubusercontent.com/84363701/121341709-81ad0300-c953-11eb-8e07-73d8c5d17278.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by khimpVasavah** [comment]
Deliverables will be replaced by competency when you checked "has default competency" and the deliverable that you input before checking the "has default competency" will not be returned. perhaps we should place a confirm message upon checking the checkbox.

**Comment by Peterdelapena** [comment]
Placing a confirmation message checkbox is a good idea, will check if it would be a good enhancement for the application. Otherwise, We'll mark it as an invalid ticket.
