### ISSUE TITLE
A specific employees  not reflected in the Regenerated DTRS

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#61]
**Describe the bug**
The accounts of Gemma Cariño and Mechie Alanis were not reflected in the Regenerated DTRS May 1-31. Tried to unlock twice but the same was not appear. They were on CO/JOS register as said on their profile but their accounts is existing on the regular register.

**To Reproduce**
1. Go to  CO/JOS register
2. Click on regenerate dtr
3. Scroll down to dtr
4. Cariño and Alanis has no dtr

**Expected behavior**
System should Generate Cariño and Alanis DTR on CO/JOS register as said on their profile.

**Screenshots**
![ticket1](https://user-images.githubusercontent.com/84363875/121462045-8a98e580-c9e2-11eb-812b-1dc5ec301d5e.PNG)

**Additional context**

**Comment by Peterdelapena** [comment]
Ticket closed
