### ISSUE TITLE
UNABLE TO SET AN APPROVER TO SAME ACCOUNT

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#62]
**Describe the bug**
The User was unable to set an approver to the same account. 

**To Reproduce**
1. Go to 'HR-> Employees'
2. Click on an Account
3. Scroll down to 'Approval Matrix'
4. Select the same account as an approver
5. Click 'Save changes'
6. Click 'Refresh page'
7. See error

**Expected behavior**
The changes to the approval matrix should reflect throughout the system even after refreshing the whole page

**Screenshots**
Changes to approval matrix was done:
![image](https://user-images.githubusercontent.com/84363701/121505838-c13c2380-ca15-11eb-8154-12d92ada92bb.png)

After Refreshing:
![image](https://user-images.githubusercontent.com/84363701/121506016-efb9fe80-ca15-11eb-8246-9d22748d209b.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by AnyaCee** [comment]
bug has been fixed. marked as closed
