### ISSUE TITLE
Filter for dashboard also appears on Requestor and BA Interface

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#65]
**Describe the bug**
Filter for dashboard also appears on Requestor and BA Interface even though these accounts don't have an access on dashboards

**Expected behavior**
There should be no filter for dashboards in the interface of Requestor and BA

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/121659348-ca3ffa00-cad4-11eb-8372-4a316553cd05.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Ticket is valid

**Comment by Peterdelapena** [comment]
Filter selection still appearing in the loading interface of the system
![image](https://user-images.githubusercontent.com/84363701/121871406-a845b200-cd36-11eb-8ec3-020febb4ff58.png)

**Comment by AnyaCee** [comment]
bug has been fixed marked as closed
