### ISSUE TITLE
View and edit on a certain Talent requisition are not responding

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#66]
**Describe the bug**
Upon clicking the View or Edit button to a certain Talent requisition, the page loads to a white screen to some of the applications

**To Reproduce**
1. Go to 'Talent requisition'
2. Click on 'View' or 'Edit'
3. See the error

**Expected behavior**
The system should load to the correct landing page of the certain
application

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/121851365-978a4180-cd20-11eb-8708-106381fd522a.png)
![image](https://user-images.githubusercontent.com/84363701/121851409-a83ab780-cd20-11eb-8dc1-304c537c5517.png)

**Desktop (please complete the following information):**
- OS: [win10]
- Browser [chrome]
- Version [90.0.4430.212]

**Additional context**
Ticket will be marked as pending

**Comment by AnyaCee** [comment]
marked as closed
