### ISSUE TITLE
THERE ARE NO DETAILS IN THE WORK EXPERIENCE OF ALL THE JOB OPENINGS

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#70]
**Describe the bug**
Upon viewing the list of the job openings, the Work experience column doesn't have data on it, even though it has in the system.

**Expected behavior**
Work experience to each Job Openings should reflect even in the list

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/121864086-18e8d080-cd2f-11eb-93bd-b4493aa1c9a9.png)
![image](https://user-images.githubusercontent.com/84363701/121864159-2b630a00-cd2f-11eb-8c1f-9a4f7bb5ee92.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnyaCee** [comment]
marked as closed
