### ISSUE TITLE
DCI account which has the same role as VCI account cannot view the reports chart

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#73]
**Describe the bug**
DCI account which has the same role as the VCI account cannot view the report's chart

**Expected behavior**
DCI account should have an access to the report's chart since one of its roles is as an admin

**Screenshots**
![image](https://user-images.githubusercontent.com/84363701/121875493-19876400-cd3b-11eb-8a08-f396c661a802.png)
![image](https://user-images.githubusercontent.com/84363701/121875552-2c019d80-cd3b-11eb-99d0-51ebef4f268f.png)
VCI interface shows the Report charts
![image](https://user-images.githubusercontent.com/84363701/121875919-90bcf800-cd3b-11eb-82fe-340367e3d3f2.png)
DCI interface doesn't have a report chart even though its roles are the same as with VCI
![image](https://user-images.githubusercontent.com/84363701/121876070-b77b2e80-cd3b-11eb-92f3-dd6dddd2acef.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [90.0.4430.212]

**Additional context**
none

**Comment by AnyaCee** [comment]
issue has been fixed, marked as closed
