### ISSUE TITLE
Requestor should not be available to assign a ticket

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#75]
**Is your feature request related to a problem? Please describe.**

question: shouldn't the other roles not be included in assigning the ticket to? Requestor is available to be assigned a ticket, does not show deviation from other roles.

**Describe the solution you'd like**
Requestor should not be available to assign a ticket

**Comment by AnyaCee** [comment]
requestor should not have same bottom section as the admin roles

**Comment by Peterdelapena** [comment]
Ticket closed
