### ISSUE TITLE
TIME KEEPING SETTINGS IS NOT EDITABLE ON MANAGERS REGISTER

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#79]
**Describe the bug**
 When editing on the time keeping settings under register rules and click save changes button. Save changes doesn't change the rules.

**To Reproduce**
1. Go to register rules under register
2. Click on time keeping settings
3. click save changes
4. doesn't change the rules.

**Expected behavior**
System should update the rules

**Screenshots**
![tks](https://user-images.githubusercontent.com/84363875/122009150-5f503500-cdec-11eb-8909-398ecb1eef5c.PNG)
![tks2](https://user-images.githubusercontent.com/84363875/122009154-5fe8cb80-cdec-11eb-8d2e-196526e1fd2e.PNG)

**Comment by Peterdelapena** [comment]
Fixes validated, Ticket marked as closed
