### ISSUE TITLE
APPROVED OVERTIME DIDN'T REFLECT ON DTR AND TAR

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#80]
**Describe the bug**
THE APPROVED OVERTIME APPLICATIONS DIDN'T REFLECT ON DTR AND TAR

**To Reproduce**
1. Go to 'Register'
2. Regenerate the payroll
3. Click on 'DTR' of a certain employee
5. Click on 'TAR' of a certain employee
6. See error

**Expected behavior**
The approved overtime application s of the certain employee should reflect on the regenerated payroll 

**Screenshots**
Approved OT and NDOT in the overtime history
![image](https://user-images.githubusercontent.com/84363701/122008337-835f4680-cdeb-11eb-9c7a-5f5379f0a965.png)
No recorded OT and NDOT on DTR
![image](https://user-images.githubusercontent.com/84363701/122008276-6b87c280-cdeb-11eb-89cd-0464facec9db.png)
![image](https://user-images.githubusercontent.com/84363701/122008314-7b9fa200-cdeb-11eb-8a0e-390f2d543336.png)
No recorded OT and NDOT on TAR
![image](https://user-images.githubusercontent.com/84363701/122008489-b1dd2180-cdeb-11eb-8993-7784e38c8436.png)
![image](https://user-images.githubusercontent.com/84363701/122008538-c3bec480-cdeb-11eb-9f7f-a94e935e751a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
none

**Comment by AnyaCee** [comment]
the bug has been fixed, marked as closed.
