### ISSUE TITLE
Update logo of TBI

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#85]
**Is your feature request related to a problem? Please describe.**
Pls update the logo of the system into the TBI logo

**Additional context**
![image](https://user-images.githubusercontent.com/84363701/122192836-96931480-cec6-11eb-845f-3ea2fc5efd7b.png)

**Comment by AnyaCee** [comment]
logo already emailed by sir Joe

**Comment by Peterdelapena** [comment]
Fixes validated, Ticket will mark as closed
