### ISSUE TITLE
"Roles" on profile should be removed

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#89]
**Is your feature request related to a problem? Please describe.**
Users can't understand what "Roles" are for

**Describe the solution you'd like**
Remove roles under profile

**Additional context**

**Comment by Peterdelapena** [comment]
Roles removed
![image](https://user-images.githubusercontent.com/84363701/122503725-8e081e80-d02b-11eb-8b44-48bc232e0e4b.png)
Ticket marked as closed
