### ISSUE TITLE
When click the queue word or home icon the system stuck on loading

### ISSUE THREAD

**Issue by AnyaCee** [vasavah/vasavah-qa-trainees#95]
**Describe the bug**
When click the queue word or home icon the system stuck on loading

**To Reproduce**
1. Go to queues
2. Click on queue word or home icon
3. The system stuck on loading

**Expected behavior**
System should load and not be stuck on loading

**Screenshots**
![queue](https://user-images.githubusercontent.com/84363875/122198577-dc061080-cecb-11eb-935f-38e8f2c0f8ef.PNG)
![queuel](https://user-images.githubusercontent.com/84363875/122198572-db6d7a00-cecb-11eb-9bba-a65409e4f760.PNG)

**Comment by Peterdelapena** [comment]
![image](https://user-images.githubusercontent.com/84363701/122503574-471a2900-d02b-11eb-90ab-5cff945a0e4e.png)
upon creating a ticket
