### ISSUE TITLE
Approves can be tagged for approvals then enter Approved in the requestor comments section

### ISSUE THREAD

**Issue by Peterdelapena** [vasavah/vasavah-qa-trainees#97]
**Is your feature request related to a problem? Please describe.**
Approves can be tagged for approvals then enter Approved in the requestor comments section

![image](https://user-images.githubusercontent.com/84363701/122326897-9a26aa00-cf5f-11eb-8396-afae66f0de3d.png)

**Comment by AnyaCee** [comment]
issue has been fixed, marked as closed
